apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: staffofhades/moderation
          env:
            - name: PORT
              value: "4003"
            - name: EVENTS_SERVICE
              value: "http://event-bus-clusterip-srv:4005"
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-clusterip-srv
spec:
  type: ClusterIP # Optional; default value
  selector:
    app: moderation
  ports:
    - name: moderation-clusterip
      protocol: TCP
      port: 4003
      targetPort: 4003
