apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: staffofhades/query
          env:
            - name: PORT
              value: "4002"
            - name: EVENTS_SERVICE
              value: "http://event-bus-clusterip-srv:4005"
---
apiVersion: v1
kind: Service
metadata:
  name: query-clusterip-srv
spec:
  type: ClusterIP # Optional; default value
  selector:
    app: query
  ports:
    - name: query-clusterip
      protocol: TCP
      port: 4002
      targetPort: 4002
