apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: staffofhades/blog:dev-latest
          env:
            - name: PORT
              value: "4200"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-clusterip-srv
spec:
  type: ClusterIP # Optional; default value
  selector:
    app: blog
  ports:
    - name: blog-clusterip
      protocol: TCP
      port: 4200
      targetPort: 4200
