apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: staffofhades/comments:dev-latest
          env:
            - name: PORT
              value: "4001"
            - name: EVENTS_SERVICE
              value: "http://event-bus-clusterip-srv:4005"
---
apiVersion: v1
kind: Service
metadata:
  name: comments-clusterip-srv
spec:
  type: ClusterIP # Optional; default value
  selector:
    app: comments
  ports:
    - name: comments-clusterip
      protocol: TCP
      port: 4001
      targetPort: 4001
